apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      name: demo
      labels:
        app: demo
    spec:
      containers:
        - name: demo
          image: demo
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000

---
kind: Service
apiVersion: v1
metadata:
  name: demo
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: demo

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
metadata:
  annotations:
    traefik.ingress.kubernetes.io/pass-client-tls-cert: |
      pem: true
      infos:
        notafter: true
        notbefore: true
        sans: true
        subject:
          country: true
          province: true
          locality: true
          organization: true
          commonname: true
          serialnumber: true
  name: demo
spec:
  rules:
    - host: demo.m.local
      http:
        paths:
          - path: /
            backend:
              serviceName: demo
              servicePort: 3000
